object FormCadastro: TFormCadastro
  Left = 0
  Top = 0
  Caption = 'Cadastro'
  ClientHeight = 437
  ClientWidth = 642
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object GroupBox1: TGroupBox
    Left = 0
    Top = 0
    Width = 642
    Height = 177
    Align = alTop
    Caption = 'Cliente'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clMenuText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentColor = False
    ParentFont = False
    TabOrder = 0
    object DBEditNome: TDBEdit
      Left = 32
      Top = 55
      Width = 297
      Height = 21
      DataField = 'CLI_NOME'
      DataSource = DataSource1
      Enabled = False
      TabOrder = 0
    end
    object DBEditCpf: TDBEdit
      Left = 360
      Top = 55
      Width = 209
      Height = 21
      DataField = 'CLI_CPF'
      DataSource = DataSource1
      Enabled = False
      TabOrder = 1
    end
    object DBEditTelefone: TDBEdit
      Left = 32
      Top = 111
      Width = 209
      Height = 21
      DataField = 'CLI_TELEFONE'
      DataSource = DataSource1
      Enabled = False
      TabOrder = 2
    end
    object StaticText5: TStaticText
      Left = 32
      Top = 32
      Width = 31
      Height = 17
      ParentCustomHint = False
      Caption = 'Nome'
      Color = clWhite
      DoubleBuffered = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMenuText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentDoubleBuffered = False
      ParentFont = False
      TabOrder = 3
      Transparent = False
    end
    object StaticText1: TStaticText
      Left = 32
      Top = 88
      Width = 60
      Height = 17
      ParentCustomHint = False
      Caption = 'Telefone(*)'
      Color = clWhite
      DoubleBuffered = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMenuText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentDoubleBuffered = False
      ParentFont = False
      TabOrder = 4
      Transparent = False
    end
    object StaticText3: TStaticText
      Left = 360
      Top = 32
      Width = 23
      Height = 17
      ParentCustomHint = False
      Caption = 'CPF'
      Color = clWhite
      DoubleBuffered = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMenuText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentDoubleBuffered = False
      ParentFont = False
      TabOrder = 5
      Transparent = False
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 392
    Width = 642
    Height = 45
    Align = alBottom
    Color = 2697513
    ParentBackground = False
    TabOrder = 1
    object BtnIncluir: TButton
      Left = 1
      Top = 1
      Width = 77
      Height = 43
      Align = alLeft
      Caption = 'Incluir'
      TabOrder = 0
      OnClick = BtnIncluirClick
    end
    object BtnGravar: TButton
      Left = 491
      Top = 1
      Width = 75
      Height = 43
      Align = alRight
      Caption = 'Gravar'
      Enabled = False
      TabOrder = 1
      OnClick = BtnGravarClick
    end
    object BtnCancelar: TButton
      Left = 566
      Top = 1
      Width = 75
      Height = 43
      Align = alRight
      Caption = 'Cancelar'
      Enabled = False
      TabOrder = 2
      OnClick = BtnCancelarClick
    end
  end
  object GroupBox2: TGroupBox
    Left = 0
    Top = 177
    Width = 642
    Height = 120
    Align = alTop
    Caption = 'Parente (Opicional)'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentColor = False
    ParentFont = False
    TabOrder = 2
    object DBEdit1: TDBEdit
      Left = 32
      Top = 35
      Width = 297
      Height = 21
      DataField = 'NOME_PARENTE'
      DataSource = DSparentes
      Enabled = False
      TabOrder = 0
    end
    object StaticText4: TStaticText
      Left = 32
      Top = 17
      Width = 45
      Height = 17
      ParentCustomHint = False
      Caption = 'Nome(*)'
      Color = clWhite
      DoubleBuffered = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMenuText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentDoubleBuffered = False
      ParentFont = False
      TabOrder = 1
      Transparent = False
    end
    object StaticText6: TStaticText
      Left = 32
      Top = 62
      Width = 60
      Height = 17
      ParentCustomHint = False
      Caption = 'Telefone(*)'
      Color = clWhite
      DoubleBuffered = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMenuText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentDoubleBuffered = False
      ParentFont = False
      TabOrder = 2
      Transparent = False
    end
    object DBEdit3: TDBEdit
      Left = 360
      Top = 35
      Width = 209
      Height = 21
      DataField = 'CPF_PARENTE'
      DataSource = DSparentes
      Enabled = False
      TabOrder = 3
    end
    object StaticText8: TStaticText
      Left = 360
      Top = 17
      Width = 37
      Height = 17
      ParentCustomHint = False
      Caption = 'CPF(*)'
      Color = clWhite
      DoubleBuffered = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMenuText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentDoubleBuffered = False
      ParentFont = False
      TabOrder = 4
      Transparent = False
    end
    object DBEdit5: TDBEdit
      Left = 32
      Top = 79
      Width = 209
      Height = 21
      DataField = 'TELL_PARENTE'
      DataSource = DSparentes
      Enabled = False
      TabOrder = 5
    end
  end
  object DataSource1: TDataSource
    DataSet = DM.queryCli
    Left = 592
    Top = 96
  end
  object DSparentes: TDataSource
    DataSet = DM.queryParentes
    Left = 504
    Top = 96
  end
end
